name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

env:
  CARGO_TERM_COLOR: always

jobs:
  typos:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Spell check
        uses: crate-ci/typos@master

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2025-09-05
          components: rustfmt, clippy, llvm-tools-preview, rustc-dev
      - name: Cache on ${{ github.ref_name }}
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: warm
      - name: Check formatting
        run: cargo fmt --check
      - name: Clippy
        run: |
          cargo +nightly-2025-09-05 clippy --all-targets -- -D warnings
          cargo +nightly-2025-09-05 clippy --all-targets --all-features -- -D warnings

  build:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            "macos-13",
            "macos-latest",
            "ubuntu-24.04",
            "ubuntu-latest",
            "windows-latest",
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: oxc-project/setup-rust@cd82e1efec7fef815e2c23d296756f31c7cdc03d # v1.0.0
        with:
          cache-key: warm
          save-cache: ${{ github.ref_name == 'main' }}
      - name: Check
        run: cargo check --all-targets
      - name: Build
        run: cargo build --tests --bins --examples
      - name: Test
        run: cargo test
        env:
          RUST_BACKTRACE: 1
  # TODO: Enable Web Platform Tests
  # wpt:
  #   name: Web Platform Tests
  #   runs-on: macos-latest
  #   timeout-minutes: 50
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Rust toolchain
  #       uses: dtolnay/rust-toolchain@master
  #       with:
  #         toolchain: "nightly-2025-09-05"
  #     - name: Cache on ${{ github.ref_name }}
  #       uses: Swatinem/rust-cache@v2
  #       with:
  #         shared-key: wpt
  #         save-if: ${{ github.ref == 'refs/heads/main' }}
  #     - name: Checkout WPT submodule
  #       run: git submodule update --init --recursive
  #     - name: Build andromeda cli
  #       run: cargo build -p andromeda --release
  #     - name: Build WPT runner
  #       run: cargo build --bin wpt_test_runner --release
  #     - name: Run WPT tests
  #       run: cargo run --bin wpt --release -- --wpt-dir tests/wpt --ci-mode
  #     - name: Generate test report
  #       if: always()
  #       run: cargo run --bin wpt_test_runner --release -- report --detailed
  #     - name: Validate test expectations
  #       if: always()
  #       run: cargo run --bin wpt_test_runner --release -- validate-expectations --wpt-dir tests/wpt
